version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - selenium  
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports: 
      - 4444:4444
    restart: always
  cuda:
      image: nvidia/cuda:11.0.3-devel-ubuntu16.04
      runtime: nvidia
      environment:
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES compute,utility
      command: nvidia-smi
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

