version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - selenium  
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports: 
      - 4444:4444
    restart: always
  nvsmi:
    image: nvidia/cuda:11.0.3-devel-ubuntu16.04
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: nvidia-smi


