version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - selenium  
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports: 
      - 4444:4444
    restart: always

              


