version: '3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - selenium  

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports: 
      - 4444:4444
    restart: always
  test:
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
              


